### PR TITLE
internal

### PR DESCRIPTION
**Pull request by julienchastang**
Don't merge quite yet. There's probably some left over cruft here as well. Plz review :-)

### CODE REVIEW

**Comment by julienchastang** [comment]
@dcamron do we need `ffmpeg` ? My guess is no, but just checking.

**Comment by dcamron** [comment]
> @dcamron do we need `ffmpeg` ? My guess is no, but just checking.

Nope!

**Comment by julienchastang** [comment]
@dcamron This PR should be ready at this point :-)

**Review by dcamron — APPROVED** [review]
👍

**Pull request merged**
